# site settings
title: Lilia The Brazilian
subtitle: A Visual Note Taker and UX Designer
email: hi@lilianthebrazilian.com
description: And I really love to sketch and create awesome products.
baseurl: "/lilianthebrazilian"

#destination
destination: ./docs

permalink: "/:path"

# Collections
collections:
  posts:
    output: true
  work:
    output: true
    permalink: "/work/:path/"
  projects:
    output: false

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6


# image bank
image-path: "https://res.cloudinary.com/cheekybrazilian/image/upload/v1548967311/maverick-ux"
portfolio-path: "https://res.cloudinary.com/cheekybrazilian/image/upload/v1549398214/maverick-ux/portfolio/"
process-path: "https://res.cloudinary.com/cheekybrazilian/image/upload/v1549398214/maverick-ux/process/"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: page
  - scope:
      path: "/work"
    values:
      layout: work
  - scope:
      path: "/process"
    values:
      layout: process



# Themes
#theme: jekyll-theme-cayman

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-feed

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: https://gitlab.com/u/itagiba
googleplus_url: https://plus.google.com/u/0/+Spotdd
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/Lilian-Itagiba
pinterest_url:
slack_url:
twitter_url: https://twitter.com/spotdd
