---
title: Lilia The Brazilian
timezone: UTC
collections:
  authors:
    title: Authors
    output: true
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
    permalink: "/projects/:path/"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: authors
  values:
    layout: author
- scope:
    path: ''
    type: posts
  values:
    layout: post
- scope:
    path: ''
  values:
    layout: page
subtitle: A Visual Note Taker and UX Designer
email: hi@lilianthebrazilian.com
description: A responsive site template designed by the one and only<br /> and released
  with the help of github.
baseurl: "/lilianthebrazilian"
permalink: "/:path"
tiles-source: pages
tiles-count: 6
plugins:
- jekyll-seo-tag
- jekyll-feed
500px_url: 
facebook_url: 
github_url: 
gitlab_url: https://gitlab.com/u/itagiba
googleplus_url: https://plus.google.com/u/0/+Spotdd
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/Lilian-Itagiba
pinterest_url: 
slack_url: 
twitter_url: https://twitter.com/spotdd
